Repository wecode-bootcamp-korea/17-1st-SweetHome-frontend, pull requests merged in 2021-02, with the labels that each got.

#2 [17기 곽진석] footer 리뷰내용 수정
  public/index.html
  src/Components/Footer/BrandInformData.js
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Footer/InformationInFooter/InformationData/InformationData.js
  src/Components/Footer/InformationInFooter/InformationData/InformationData.scss
  src/Components/Footer/InformationInFooter/InformationInFooter.js
  src/Components/Footer/InformationInFooter/InformationInFooter.scss
  src/Components/Footer/NavInFooter/ContentInNav/ContentInNav.js
  src/Components/Footer/NavInFooter/ContentInNav/ContentInNav.scss
  src/Components/Footer/NavInFooter/NavInFooter.js
  src/Components/Footer/NavInFooter/NavInFooter.scss
  src/Routes.js
  src/index.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: Status: Accepted

#4 [17기 김종진] 상품페이지 사이드바 동적 구현/ 상품 리스트-> 상품 디테일 페이지 동적라우팅 작업중
  package-lock.json
  package.json
  public/data/ProductList.json
  public/data/ProductMenu.json
  src/Pages/ProductMain/ProductCategory/MainCategory/MainCategory.js
  src/Pages/ProductMain/ProductCategory/MainCategory/MainCategory.scss
  src/Pages/ProductMain/ProductCategory/ProductCategory.js
  src/Pages/ProductMain/ProductCategory/ProductCategory.scss
  src/Pages/ProductMain/ProductList/ProductList.js
  src/Pages/ProductMain/ProductList/ProductList.scss
  src/Pages/ProductMain/ProductList/categoryFilter/categoryFilter.js
  src/Pages/ProductMain/ProductList/mockdata.js
  src/Pages/ProductMain/ProductMain.js
  src/Pages/ProductMain/ProductMain.scss
  src/Pages/ProductMain/Slide/Slide.js
  src/Pages/ProductMain/Slide/Slide.scss
  src/Pages/ProductMain/Slider/Slider.js
  src/Pages/ProductMain/Slider/Slider.scss
  src/Routes.js
Labels: Status: Accepted

#6 [17기 곽진석] SignUp 리뷰내용 구현 및 질문
  public/index.html
  src/Pages/SignUp/SignUp.js
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/mainInSignUp/checkInInput/checkBoxData.js
  src/Pages/SignUp/mainInSignUp/checkInInput/checkBoxGroup/checkBox/checkBox.js
  src/Pages/SignUp/mainInSignUp/checkInInput/checkBoxGroup/checkBox/checkBox.scss
  src/Pages/SignUp/mainInSignUp/checkInInput/checkBoxGroup/checkBoxGroup.js
  src/Pages/SignUp/mainInSignUp/checkInInput/checkBoxGroup/checkBoxGroup.scss
  src/Pages/SignUp/mainInSignUp/checkInInput/checkInInput.js
  src/Pages/SignUp/mainInSignUp/checkInInput/checkInInput.scss
  src/Pages/SignUp/mainInSignUp/inputInSignUp/inputInSignUp.js
  src/Pages/SignUp/mainInSignUp/inputInSignUp/inputInSignUp.scss
  src/Pages/SignUp/mainInSignUp/mainInSignUp.js
  src/Pages/SignUp/mainInSignUp/mainInSignUp.scss
  src/Routes.js
Labels: Status: 리뷰 진행중

#7 [17기 김민주] 상품 상세페이지 컨플릭트 완료
  package-lock.json
  package.json
  public/data/MockData.json
  public/data/ReviewData.json
  src/Images/minjoo/cancel.svg
  src/Images/minjoo/letterX.svg
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductReview/Card.js
  src/Pages/ProductDetail/ProductReview/Card.scss
  src/Pages/ProductDetail/ProductReview/CardList.js
  src/Pages/ProductDetail/ProductReview/ProductReview.js
  src/Pages/ProductDetail/ProductReview/ProductReview.scss
  src/Pages/ProductDetail/ProductReview/ReviewModal.js
  src/Pages/ProductDetail/ProductReview/ReviewModal.scss
  src/Pages/ProductDetail/ProductReview/StarRated.js
  src/Pages/ProductDetail/ProductReview/StarReadOnly.js
Labels: Status: 수정 요청

#5 [17기 곽진석]NavBar리뷰내용 반영
  src/Components/NavBar/Category/Category.js
  src/Components/NavBar/Category/Category.scss
  src/Components/NavBar/CategoryInNav/CategoryInNav.js
  src/Components/NavBar/CategoryInNav/CategoryInNav.scss
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
  src/Components/NavBar/navCategories.js
  src/Routes.js
Labels: Status: 리뷰 요청

#10 [17기 곽진석]장바구니 콤보박스 및 체크박스 기능 구현
  src/Pages/Cart/Cart.js
  src/Pages/Cart/Cart.scss
  src/Pages/Cart/mainInCart/addedProduct/addedProduct.js
  src/Pages/Cart/mainInCart/addedProduct/addedProduct.scss
  src/Pages/Cart/mainInCart/addedProduct/productInform/PRODUCTMOCKDATA.js
  src/Pages/Cart/mainInCart/addedProduct/productInform/productInform.js
  src/Pages/Cart/mainInCart/addedProduct/productInform/productInform.scss
  src/Pages/Cart/mainInCart/calculatorAndBuy/calculatorAndBuy.js
  src/Pages/Cart/mainInCart/calculatorAndBuy/calculatorAndBuy.scss
  src/Pages/Cart/mainInCart/mainInCart.js
  src/Pages/Cart/mainInCart/mainInCart.scss
  src/Pages/Cart/noProduct/noProduct.js
  src/Pages/Cart/noProduct/noProduct.scss
Labels: Status: 리뷰 요청

#9 [17기 김종진] 상품 디테일 페이지 레이아웃 밑 기본 기능 구현 완성
  public/data/MockData.json
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductInfo/ProductInfo.js
  src/Pages/ProductDetail/ProductInfo/ProductInfo.scss
  src/Routes.js
Labels: Status: 리뷰 요청

#11 [17기 곽진석] Feature/sign up 마무리
  src/Pages/SignUp/mainInSignUp/mainInSignUp.js
Labels: Status: 리뷰 요청

#13 [17기 곽진석]Feature/nav bar
  src/Components/NavBar/Category/Category.scss
  src/Components/NavBar/CategoryInNav/CategoryInNav.scss
  src/Components/NavBar/NavBar.js
  src/Components/NavBar/NavBar.scss
Labels: Status: 리뷰 요청

#14 [17기 김종진] 상품 메인페이지 머지요청
  public/data/FilterBar.json
  public/data/ProductList.json
  public/data/ProductMenu.json
  src/Pages/ProductMain/ProductCategory/MainCategory/MainCategory.js
  src/Pages/ProductMain/ProductCategory/MainCategory/MainCategory.scss
  src/Pages/ProductMain/ProductCategory/ProductCategory.js
  src/Pages/ProductMain/ProductEventList/ProductEventList.js
  src/Pages/ProductMain/ProductEventList/ProductEventList.scss
  src/Pages/ProductMain/ProductList/ProductList.js
  src/Pages/ProductMain/ProductList/ProductList.scss
  src/Pages/ProductMain/ProductList/mockdata.js
  src/Pages/ProductMain/ProductMain.js
  src/Pages/ProductMain/ProductMain.scss
  src/Pages/ProductMain/Slide/BannerSlide.js
  src/Pages/ProductMain/Slide/BannerSlider.scss
Labels: Status: 컨플릭트 해결 요청

#15 [17기]Feature/sweethome edit
  package-lock.json
  src/Components/NavBar/NavBar.scss
  src/Pages/SignUp/SignUp.scss
  src/Pages/SignUp/mainInSignUp/mainInSignUp.scss
Labels: Status: 리뷰 요청
